version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "localhost", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - back
  test:
    build:
      dockerfile: dockerfile
      no_cache: true
      target: test
      args:
        - DB_HOST=db
    depends_on:
      - db
    networks:
      - back
networks:
  back:
    driver: bridge
